### ISSUE TITLE
[Bug] Error loading script

### ISSUE THREAD

**Issue by MysticStyxxx** [overextended/ox_lib#236]
**Describe the bug**
it says:
`[script:ox_lib-master] Error loading script resource/init.lua in resource ox_lib-master: @ox_lib-master/resource/init.lua:25: Unable to load UI. Build ox_lib or download the latest release.
[script:ox_lib-master] stack traceback:
[script:ox_lib-master] 	[C]: in function 'error'
[script:ox_lib-master] 	@ox_lib-master/resource/init.lua:25: in main chunk
[    c-scripting-core] Failed to load script resource/init.lua.`

**Comment by FjamZoo** [comment]
You downloaded the source and not the BUILD UI. Go here: https://github.com/overextended/ox_lib/releases/tag/v2.21.0 to download the latest version of the BUILD UI.

If you want to use v3 and you downloaded the source because of that then you can build the resource with this tutorial: https://overextended.github.io/docs/ox_lib#building-the-ui

**Comment by MysticStyxxx** [comment]
lastest version says the same thing

**Comment by MysticStyxxx** [comment]
i'm new to this. trying my best with it
