### ISSUE TITLE
[Suggestion] Collection Class Implementation

### ISSUE THREAD

**Issue by tomiichx** [overextended/ox_lib#258]
**Is your feature request related to a problem? Please describe.**
This feature request isn't related to any problem, but simply a design pattern recommendation for better, consistent and more readable code. Not necessarily required, but a nice thing to have in my opinion.
After working for some time with [collections](https://laravel.com/docs/10.x/collections) in Laravel and coming back to Lua after a couple of months, it started to bother me when working with tables (arrays) and handling large loads of data.

**Describe the solution you'd like**
I would like a collection class implementation in the library (which I use for basically everything nowadays, that's why I'm recommending this here). It makes the code more 'modular', easier to understand and maintain so to say. I will provide a few examples down below.
> [Found something similar to what it'd look like, but this is outdated can be improved a lot...](https://github.com/imliam/Lua-Collections)

**Additional context**
Code Examples:
```
-- Regular usage: (this is what would be implemented in the lib so you can use the example down below)
local numbers = {5, 10, 50}

local max = numbers[1]
for i = 2, #numbers do
  if numbers[i] > max then
    max = numbers[i]
  end
end
print("Max found: " .. max)

-- Collection class usage:
collect({5, 10, 50}):max():all(true)

--[[
collect({5, 10, 50}) -- "collect" our data
  :max() -- do the same for loop from above in one line. This is just one method, one example.
  :all(true) -- return back everything (boolean parameter to also encode and print the data when returning)
]]
````

**Comment by tomiichx** [comment]
You can take a look in the links above for more examples and methods like each, map, where...

**Comment by thelindat** [comment]
Collections are somewhat out of scope with what I'd like to include or support; once we adopt something into the codebase, we're expected to maintain it as our own. The Lua module you linked has 91 of 139 different methods and may need further changes for CfxLua on top of writing out all the other methods. The time investment compared to the number of people that would use them would hardly be worthwhile for me.

ox_lib is generally intended for FiveM related modules or simple reusable modules (e.g. lib.table), ignoring UI stuff which got out of hand because of peoples wants. I made this resource primarily for myself to utilise in my own resources, rather than for the community - so unless I have a need for something it's unlikely to be added.

**Comment by tomiichx** [comment]
I understand, thank you for the answer! 👍🏼
