### ISSUE TITLE
If the label of a radial-item is too long it just cuts off

### ISSUE THREAD

**Issue by ItzTrivial** [overextended/ox_lib#262]
**Describe the bug**
If the label of a radial-item is too long it just cuts off

**To Reproduce**
1. Create long lable
2. Witness how its cut off instead of forcing a new line oe.

**Expected behavior**
Label should fit in the radialmenu

**Comment by Moozdzn** [comment]
From the docs: [When adding radial menu items whether they are global or for a sub menu, make sure to stick to short as possible labels as long labels will look out of place and should not be used with the radial menu because of it's density.](https://overextended.github.io/docs/ox_lib/Interface/Client/radial#usage-example)
Unsure if this can be considered a bug, I suggest making your labels shorter

**Comment by thelindat** [comment]
We asked him to make an issue so we don’t forget; labels are a little too short at this time and if your language is verbose can make it hard to define even a simple action.

**Comment by bbeckann** [comment]
how can i create radial menu using ox.lib
