### ISSUE TITLE
[Suggestion] Possibility to have no Title.

### ISSUE THREAD

**Issue by zf-development** [overextended/ox_lib#428]
**Is your feature request related to a problem? Please describe.**
It's kinda frustrating to need to make a button look like this because you want to have only like "details" and make "splitters". There is always a space between the description and the top that is an obligation because if you don't make the title = ' ' then the title is a **"1"**

**Describe the solution you'd like**
Remove the obligation for a title.

**Additional context**
![image](https://github.com/overextended/ox_lib/assets/48424078/5a72503b-8ace-4856-afe9-d1120aa3a658)
![image](https://github.com/overextended/ox_lib/assets/48424078/b9c0ca44-aef8-4b90-802b-7fe7afe89ead)

**Comment by LukeWasTakenn** [comment]
A change like this would probably cause issues with the, though deprecated, key-value approach of defining the menu items, where the key is the title of the button and the value is an object of it's props.

**Comment by zf-development** [comment]
Maybe instead of removing the title, if there is no title and a description make the description the object and change the <h1> for a <p>.

What are you thinking about this?

**Comment by zf-development** [comment]
Something like (I'm not an expert in js)

```ts
<Text className={button.title : classes.buttonTitleText ? classes.description}>
  <ReactMarkdown components={MarkdownComponents}>{button.title || buttonKey}</ReactMarkdown>
</Text>
```

I know it's something like that but I'm not totally sure if the code is right.

**Comment by LukeWasTakenn** [comment]
Rather than rendering the description in the place of a title, a better approach is to just conditionally render the flex box depending on whether the title is defined or not.

https://github.com/overextended/ox_lib/blob/f9a7df6422ae7ad45895365e3cbe52d412db6085/web/src/features/menu/context/components/ContextButton.tsx#L108-L126

A change a like this wouldn't really work for the key-value approach of defining buttons, but again with it being deprecated and not really mentioned anywhere, I don't really care.
