### ISSUE TITLE
[Bug] Cron Doesn't Always Execute

### ISSUE THREAD

**Issue by Manason** [overextended/ox_lib#457]
**Describe the bug**
Observed that a cron isn't always executing. There seems to be something on initialization that determines whether the cron will execute or not; perhaps a conflict or a race condition. No errors in F8 or server console.

**To Reproduce**
1. Create two cron jobs
```lua
lib.cron.new('*/1 * * * *', function()
   lib.print.info("cron1")
end

lib.cron.new('*/15 * * * *', function()
   lib.print.info("cron2")
end
```
2. Restart the server until prints are no longer occurring

**Expected behavior**
Cron1 should execute every minute

**Comment by jellyton69** [comment]
Yeah, this has been an issue for a long time now. There was some discussion in this issue: https://github.com/overextended/ox_lib/issues/368

A fix was implemented, but it got nullified in a later update.

**Comment by thelindat** [comment]
In the 3 weeks since you opened this issue my cron has not failed once on startup (or overtime) using just the two tasks in my test script. The only thing I could think of - but not test - is the server hitching on startup (i.e. loading a lot of maps, vehicles, etc).

No "fix" was ever implemented for this issue in the past, and it was never reproable; and in fact you said they run "once on startup and then never again"; while the reported issue is the task _never executing_. Having multiple different issues being brought up in a single issue is also a nuisance for tracking and resolving.
