### ISSUE TITLE
Radial Menu Features

### ISSUE THREAD

**Issue by Jamie9192** [overextended/ox_lib#470]
The ability to add canUse as a function to a radial option, that hides the option when the condition is not met

ideally working recursively to hide the "parent" submenu if no "children" submenus are useable :D

**Comment by ItsANoBrainer** [comment]
Should probably be named "disabled" to match the scheme of other oxlib interface items that match this use-case. 

Might look at this at some point to implement myself.

**Comment by Vyve-AU** [comment]
> Should probably be named "disabled" to match the scheme of other oxlib interface items that match this use-case. 
> 
> Might look at this at some point to implement myself.

Or `canInteract` like ox_target.

I was able to implement it myself easily, though probably not in a way that would be up to the standards expected.

I'm sure if the overextended team desired the implementation they could also do it in ~5 minutes.

**Comment by LukeWasTakenn** [comment]
You can handle for all of the interaction with `addRadialItem` and `removeRadialItem`, and for the sub menu when you want to display something conditionally you can just reregister the menu before showing it.

And there's definitely not a need for `canInteract` lixe ox_target because the radial menu isn't like ox_target.
